### ISSUE TITLE
Send accept-version: ~8 header

### ISSUE THREAD

**Issue by geek** [joyent/webconsole-cloudapi-client#1]

**Comment by cjihrig** [comment]
For reference: https://apidocs.joyent.com/cloudapi/#issuing-requests

**Comment by reverentgeek** [comment]
should this allow for an override `api-version` on a per-fetch basis, as part of the options?

**Comment by reverentgeek** [comment]
Never mind, I think it already supports that scenario.

**Comment by geek** [comment]
fixed by https://github.com/joyent/cloudapi-client/pull/3
